add icons file for commit nanomap

diff --git a/.github/workflows/render_nanomaps.yml b/.github/workflows/render_nanomaps.yml
--- a/.github/workflows/render_nanomaps.yml
+++ b/.github/workflows/render_nanomaps.yml
@@ -39,33 +39,21 @@ jobs:
           git config --local user.email "action@github.com"
           git config --local user.name "NanoMap Generation"
 
-          CURRENT_BRANCH=$GITHUB_REF_NAME
+          git checkout -B nanomap-render
+          git add icons/_nanomaps/
 
-          git add --all
-          git stash -u
-
-          if git fetch origin nanomap-render; then
-            git checkout nanomap-render
-            git merge "origin/$CURRENT_BRANCH" --strategy-option theirs --allow-unrelated-histories -m "Merge branch '$CURRENT_BRANCH' into nanomap-render" || true
-          else
-            git checkout -b nanomap-render
-          fi
-
-          git stash pop || true
-
-          if git diff-index --quiet HEAD; then
-            echo "No changes detected."
+          if git diff-index --quiet HEAD -- icons/_nanomaps/; then
+            echo "No NanoMaps update required, skipping."
             exit 0
           fi
 
-          git add --all
           git commit -m "NanoMap Auto-Update (`date`)"
-          git push -u origin nanomap-render
+          git push -f origin nanomap-render
 
           result=$(gh pr create \
             -t "Automatic NanoMap Update" \
             -b "This pull request updates the server NanoMaps. Please review the diff images before merging." \
             -l "NanoMaps,:scroll: CL не требуется" \
             -H "nanomap-render" \
-            -B "$CURRENT_BRANCH" 2>&1) || true
+            -B "$GITHUB_REF_NAME" 2>&1) || true
           echo "$result"
